# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "ef38d52e-055c-4393-9b77-b2673f802ff3"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
    cert
    sigh

    increment_build_number(
      xcodeproj: './ios/demoApp.xcodeproj'
    )

    gym(
      scheme: 'demoApp',
      project: './ios/demoApp.xcodeproj'
    )

    pilot
end

lane :icon do
  appicon(appicon_image_file: './ios/demoApp/appIcon.png',
  appicon_devices: [:ipad, :iphone])
end
